advanced_cbv/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^basic_app/', include('basic_app.urls', namespace='basic_app')),
    # url(r'^$', views.CBView.as_view()),
    # url(r'^$', views.index, name='index'),
]

basic_app/urls.py
from django.conf.urls import url
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    url(r'^$', views.SchoolListView.as_view(), name='list'),
    # url(r'^(?P<pk>[-\w]+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    url(r'^create/$', views.SchoolCreateView, name='create'),
    url(r'^update/(?P<pk>\d+)/$',
        views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$',
        views.SchoolDeleteView.as_view(), name='delete'),
]

basic_app/models.py
from django.db import models
from django.urls import reverse


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})


class Students(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveBigIntegerField()
    school = models.ForeignKey(
        School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

basic_app/views.py
# from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, UpdateView, DeleteView
from . import models
# from django.http import HttpResponse


# def index(req):
#     return render(req, 'index.html')


# class CBView(View):
#     def get(self, request):
#         return HttpResponse("class based view")


class IndexView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme'] = 'Basic injection'
        return context


class SchoolListView(ListView):
    # define you own name
    context_object_name = 'schools'
    model = models.School  # defined by default without context_object_name: school_list
    # school_list


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School  # school by default (without context_object_name)
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(UpdateView):
    fields = ('name', 'principal', 'location')
    model = models.School
    template_name = 'basic_app/school_form.html'


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    # connect model
    model = models.School
    template_name = 'basic_app/school_conform_delete.html'
    # go back to school list after delete
    success_url = reverse_lazy("basic_app:list")

basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>CBV</title>
</head>

<body>
    <div class="container">
        <nav>
            <a href="{% url 'index' %}">Home</a>
            <a href="{% url 'basic_app:list' %}">Schools</a>
            <a href="{% url 'admin:index' %}">Admin</a>
        </nav>
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>

basic_app/templates/basic_app/school_conform_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h2>delete {{school.name}}? </h2>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="delete" class="btn btn-danger">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">cancel</a>
</form>

{% endblock %}

basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h2>School details</h2>

<div class="jumbotron school_details">
    <h3>{{school_detail.name}}</h3>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>

    <h4>Students at this school</h4>
    <!--  school_detail.all.students  come from model.py - School, related_name='students' -->
    <ul>
        {% for student in school_detail.students.all %}
        <li>
            <h5>{{student.name}}</h5>
        </li>
        {% endfor %}
    </ul>
</div>

<div class="container">
    <a href="{% url 'basic_app:update' pk=school_detail.pk %}" class="btn btn-warning">update</a>
    <a href="{% url 'basic_app:delete' pk=school_detail.pk %}" class="btn btn-danger">delete</a>
</div>

{% endblock %}

basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}

<h2>
    {% if not form.instance.pk %}
    create school
    {% else %}
    update school
    {% endif %}
</h2>

<form method="post">
    {% csrf_token %}
    <!-- enject form -->
    {{ form.as_p }}
    <input type="submit" value="submit" class="btn btn-primary">
</form>

{% endblock %}

basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<h2>List of all schools</h2>

<ul>
    {% for school in schools %}
    <li>
        <a href="{{school.id}}">{{school.name}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
        integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>CBV</title>
</head>

<body>
    <div class="container">
        <nav>
            <a href="{% url 'basic_app:list' %}">Schools</a>
            <!-- <a href="{% url 'basic_app:create' %}">Create schools</a> -->
            <a href="{% url 'admin:index' %}">Admin</a>
        </nav>
        {% block body_block %}

        {% endblock %}
    </div>

</body>

</html>

templates/index.html
{% extends "base.html" %}

{% block body_block %}
<div class="jumbotron">
    <h1>Django Advanced - CBV</h1>
    <h2>Injected contend: {{injectme}} </h2>
</div>
{% endblock %}